language: python
python:
    - 2.7
    # - 3.3 # problem with Travis, so dropping for the moment
    - 3.4
    - 3.5
    - 3.6
    - 3.7
    - pypy
    - pypy3

install:
 - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install importlib unittest2; fi
 - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then pip install --install-option='--no-cython-compile' cython ; fi
 - pip install 'coverage<4'
 - pip install coveralls

script:
 - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then python setup.py build_ext --inplace ; fi
 # PyPy is way to slow with coverage at the moment of this writing, so better avoid coverage when using PyPy
 - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]] ; then nosetests -vv --with-coverage ; else nosetests -vv ; fi

after_success:
    coveralls

notifications:
    email:
        on_success: change
        on_failure: change

# PyPy can fail because of Cython - but this should not anymore since the related unit tests are now directly skipped if running under PyPy
#matrix:
#  allow_failures:
#    - python: pypy
#    - python: pypy3

# Run these python versions with a specific distribution to ensure Travis can download and run them, from: https://github.com/travis-ci/travis-ci/issues/9133#issuecomment-531022359
matrix:
  include:
#    - python: 3.2
#      dist: trusty
    - python: 3.3
      dist: trusty
    - python: 3.7
      dist: xenial
      sudo: true
